### PR TITLE
CORE-8421 Remove unused kameleon.queries references

### PR DESCRIPTION
**Pull request by psarando**
This PR cleans up kameleon references as part of the cyverse-de/kameleon#6 effort.

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Looks reasonable to me. Is the kameleon version bump needed here, or just done since it's probably easiest? In any case, :ship:

**Comment by psarando** [comment]
Thanks for the review 👍 

I think we want to bump the kameleon version on everything that uses it after cyverse-de/kameleon#6 is merged, so that all the extra functions/queries/entities in the previous version are not compiled into services where they're not used.

**Comment by ianmcorvidae** [comment]
Sounds good to me. I just wanted to make sure I didn't miss some sort of functional reason for it that might have signaled misunderstanding of the PR!

**Comment by psarando** [comment]
So you're right, the version bump isn't necessary for these changes, but I also wanted to make sure that metadata would still compile and wasn't depending on any of the removed functions :)

**Comment by psarando** [comment]
Thanks for the review 👍

**Pull request merged**
